[package]
name = "exper-surrealdb-sets"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
surrealdb = { version = "1.5.1", features = ["kv-mem", "sql2"] }
tokio = "1.38.0"
